quarkus.banner.enabled=false
quarkus.package.jar.type=uber-jar
quarkus.package.jar.add-runner-suffix=false
# logging
quarkus.log.level=WARN
quarkus.log.console.enabled=true

# options for container build
quarkus.container-image.build=false
quarkus.jib.platforms=linux/aarch64
